### PR TITLE
removed unused adcolony and vungle plugins

### PR DESCRIPTION
**Pull request by bijoshtj**
This change is [Reviewable](https://reviewable.io/reviews/hashcube/supersonic/3)

### CODE REVIEW

**Comment by jishnu7** [comment]
can we keep it in a different branch?

People who are using it outside hashcube might need adcolony or vungle.

**Comment by bijoshtj** [comment]
@jishnu7  done using branch master-hc

**Comment by jishnu7** [comment]
LGTM

**Comment by rampr** [comment]
@jishnu7 The best way to do it would be to pass exclude during build. But this works for now.

LGTM

**Comment by rohanhc** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hashcube/supersonic/3#-:-KQ-QJ6yOs_ukK9ak1NG:bnfp4nl)_

**Pull request merged**
